import type { MetricDefinition, MetricValue } from "./models";

export const metrics: Record<string, MetricDefinition> = {
  avg: {
    id: "avg",
    version: "1",
    name: "AVG",
    fullName: "打率",
    category: "basic-hitting",
    description: "打数のうち安打になった割合。",
    interpretation: "高いほど安打を打つ頻度が高い。",
    caveat: "四球は含みません。",
    advanced: false,
    format: "rate",
    precision: 3,
  },
  hr: {
    id: "hr",
    version: "1",
    name: "HR",
    fullName: "本塁打",
    category: "basic-hitting",
    description: "対象期間に打った本塁打の本数。",
    interpretation: "多いほど本塁打による得点への貢献が大きい。",
    advanced: false,
    format: "count",
    precision: 0,
  },
  ops: {
    id: "ops",
    version: "1",
    name: "OPS",
    fullName: "出塁率 ＋ 長打率",
    category: "basic-hitting",
    description: "出塁率と長打率を足した指標。",
    interpretation: "高いほど打撃の総合的な貢献が大きい傾向。",
    caveat: "走塁や守備は含みません。",
    advanced: false,
    format: "rate",
    precision: 3,
  },
  era: {
    id: "era",
    version: "1",
    name: "ERA",
    fullName: "防御率",
    category: "basic-pitching",
    description: "9イニングあたりに許した自責点。",
    interpretation: "低いほど自責点を抑えている。",
    caveat: "守備や球場の影響があります。",
    advanced: false,
    format: "decimal",
    precision: 2,
  },
  outs: {
    id: "outs",
    version: "1",
    name: "IP",
    fullName: "投球回",
    category: "basic-pitching",
    description: "記録したアウト数をイニングで表す。",
    interpretation: "1回は3アウト。「1/3回」は1アウトです。",
    advanced: false,
    format: "outs",
    precision: 0,
  },
  barrelPct: {
    id: "barrelPct",
    version: "1",
    name: "Barrel%",
    fullName: "バレル率",
    category: "batted-ball",
    description: "長打になりやすい速度と角度を満たした打球の割合。",
    interpretation: "高いほど長打性の打球が多い。",
    caveat: "計測された打球が母数。未提供は0%ではありません。",
    advanced: true,
    format: "percent",
    precision: 1,
    percentileBasis: "performance",
    higherIsBetter: true,
  },
};
export function ratio(numerator: number, denominator: number): MetricValue {
  return denominator === 0
    ? { status: "missing", reason: "計算に必要な出場機会がありません" }
    : { status: "available", value: numerator / denominator };
}
