import type { MetricDefinition, MetricValue } from "./models";

export const metrics: Record<string, MetricDefinition> = {
  hits: { id: "hits", version: "1", name: "安打", fullName: "安打数", category: "basic-hitting",
    description: "安打の数。", interpretation: "対戦した打席数と合わせて確認します。", advanced: false, format: "count", precision: 0 },
  so: { id: "so", version: "1", name: "三振", fullName: "三振数", category: "basic-hitting",
    description: "三振の数。", interpretation: "打席数と合わせて確認します。", advanced: false, format: "count", precision: 0 },
  bb: { id: "bb", version: "1", name: "四球", fullName: "四球数", category: "basic-hitting",
    description: "四球の数。", interpretation: "打席数と合わせて確認します。", advanced: false, format: "count", precision: 0 },
  avg: {
    id: "avg",
    version: "1",
    name: "AVG",
    fullName: "打率",
    category: "basic-hitting",
    description: "打数のうち安打になった割合。",
    interpretation: "高いほど安打を打つ頻度が高い。",
    caveat: "四球は含みません。",
    advanced: false,
    format: "rate",
    precision: 3,
  },
  hr: {
    id: "hr",
    version: "1",
    name: "HR",
    fullName: "本塁打",
    category: "basic-hitting",
    description: "対象期間に打った本塁打の本数。",
    interpretation: "多いほど本塁打による得点への貢献が大きい。",
    advanced: false,
    format: "count",
    precision: 0,
  },
  ops: {
    id: "ops",
    version: "1",
    name: "OPS",
    fullName: "出塁率 ＋ 長打率",
    category: "basic-hitting",
    description: "出塁率と長打率を足した指標。",
    interpretation: "高いほど打撃の総合的な貢献が大きい傾向。",
    caveat: "走塁や守備は含みません。",
    advanced: false,
    format: "rate",
    precision: 3,
  },
  era: {
    id: "era",
    version: "1",
    name: "ERA",
    fullName: "防御率",
    category: "basic-pitching",
    description: "9イニングあたりに許した自責点。",
    interpretation: "低いほど自責点を抑えている。",
    caveat: "守備や球場の影響があります。",
    advanced: false,
    format: "decimal",
    precision: 2,
  },
  outs: {
    id: "outs",
    version: "1",
    name: "IP",
    fullName: "投球回",
    category: "basic-pitching",
    description: "記録したアウト数をイニングで表す。",
    interpretation: "1回は3アウト。「1/3回」は1アウトです。",
    advanced: false,
    format: "outs",
    precision: 0,
  },
  barrelPct: {
    id: "barrelPct",
    version: "1",
    name: "Barrel%",
    fullName: "バレル率",
    category: "batted-ball",
    description: "長打になりやすい速度と角度を満たした打球の割合。",
    interpretation: "高いほど長打性の打球が多い。",
    caveat: "計測された打球が母数。未提供は0%ではありません。",
    advanced: true,
    format: "percent",
    precision: 1,
    percentileBasis: "performance",
    higherIsBetter: true,
  },
  obp: { id: "obp", version: "1", name: "OBP", fullName: "出塁率", category: "basic-hitting",
    description: "打席で出塁した割合。", interpretation: "高いほど出塁機会を作る。", advanced: false, format: "rate", precision: 3 },
  slg: { id: "slg", version: "1", name: "SLG", fullName: "長打率", category: "basic-hitting",
    description: "1打数あたりに得た塁打。", interpretation: "高いほど長打力がある。", advanced: false, format: "rate", precision: 3 },
  kPct: { id: "kPct", version: "1", name: "K%", fullName: "三振割合", category: "sabermetrics",
    description: "対象打席または対戦打者のうち三振した割合。", interpretation: "打者は低いほど三振が少なく、投手は高いほど三振を奪う。", advanced: false, format: "percent", precision: 1 },
  bbPct: { id: "bbPct", version: "1", name: "BB%", fullName: "四球割合", category: "sabermetrics",
    description: "対象打席または対戦打者のうち四球になった割合。", interpretation: "打者は高いほど四球を選び、投手は低いほど四球を抑える。", advanced: false, format: "percent", precision: 1 },
  usagePct: { id: "usagePct", version: "1", name: "使用率", fullName: "球種使用率", category: "pitching-analysis",
    description: "対象投球に占める球種の割合。", interpretation: "高いほどその球を多く投げている。", advanced: false, format: "percent", precision: 1 },
  whiffPct: { id: "whiffPct", version: "1", name: "Whiff%", fullName: "空振り率", category: "pitching-analysis",
    description: "スイングのうち空振りになった割合。", interpretation: "投手は高いほど空振りを生み、打者は低いほど空振りが少ない。", advanced: true, format: "percent", precision: 1 },
  chasePct: { id: "chasePct", version: "1", name: "Chase%", fullName: "ボール球スイング率", category: "pitching-analysis",
    description: "ゾーン外の球に対するスイング割合。", interpretation: "投手側では高いほどボール球を振らせている。", advanced: true, format: "percent", precision: 1 },
  zonePct: { id: "zonePct", version: "1", name: "Zone%", fullName: "ゾーン内投球率", category: "pitching-analysis",
    description: "投球のうちストライクゾーン内だった割合。", interpretation: "高いほどゾーン内へ投げている。", advanced: true, format: "percent", precision: 1 },
  cswPct: { id: "cswPct", version: "1", name: "CSW%", fullName: "見逃し・空振り率", category: "pitching-analysis",
    description: "見逃しストライクと空振りの合計を投球数で割った割合。", interpretation: "高いほど打者が対応しにくい球が多い。", advanced: true, format: "percent", precision: 1 },
  swingPct: { id: "swingPct", version: "1", name: "Swing%", fullName: "スイング率", category: "pitching-analysis",
    description: "投球に対してスイングした割合。", interpretation: "高いほど打者がバットを出している。", advanced: true, format: "percent", precision: 1 },
  xwoba: { id: "xwoba", version: "1", name: "xwOBA", fullName: "期待加重出塁率", category: "sabermetrics",
    description: "打球内容と結果から期待される攻撃価値。", interpretation: "打者は高いほど、投手は低いほど良い傾向。", advanced: true, format: "rate", precision: 3 },
  hardHitPct: { id: "hardHitPct", version: "1", name: "Hard-Hit%", fullName: "強い打球の割合", category: "batted-ball",
    description: "基準以上の打球速度を記録した打球の割合。", interpretation: "高いほど強い打球が多い。", advanced: true, format: "percent", precision: 1 },
  avgVelocity: { id: "avgVelocity", version: "1", name: "平均球速", fullName: "平均投球速度", category: "pitching-analysis",
    description: "対象投球の平均速度。", interpretation: "球種や期間と合わせて読む。", advanced: false, format: "decimal", precision: 1 },
  maxVelocity: { id: "maxVelocity", version: "1", name: "最高球速", fullName: "最高投球速度", category: "pitching-analysis",
    description: "対象投球で最も速かった球。", interpretation: "少数の投球だけで傾向を決めない。", advanced: true, format: "decimal", precision: 1 },
  spinRate: { id: "spinRate", version: "1", name: "回転数", fullName: "投球回転数", category: "pitching-analysis",
    description: "投球の1分あたり回転数。", interpretation: "球種・球速と一緒に比較する。", advanced: true, format: "count", precision: 0 },
  whip: { id: "whip", version: "1", name: "WHIP", fullName: "1投球回あたり走者許容数", category: "basic-pitching",
    description: "与四球と被安打を投球回で割った値。", interpretation: "低いほど走者を出していない。", advanced: false, format: "decimal", precision: 2 },
  opponentAvg: { id: "opponentAvg", version: "1", name: "被AVG", fullName: "被打率", category: "basic-pitching",
    description: "対戦した打者の打率。", interpretation: "低いほど安打を許していない。", advanced: false, format: "rate", precision: 3 },
  opponentOps: { id: "opponentOps", version: "1", name: "被OPS", fullName: "被出塁率と被長打率の和", category: "basic-pitching",
    description: "相手打者の出塁率と長打率の合計。", interpretation: "低いほど打撃結果を抑えている。", advanced: false, format: "rate", precision: 3 },
  xba: { id: "xba", version: "1", name: "xBA", fullName: "期待打率", category: "sabermetrics",
    description: "打球の質から見積もる安打の出やすさ。", interpretation: "打者は高いほど良い打球が多い。", advanced: true, format: "rate", precision: 3 },
  xslg: { id: "xslg", version: "1", name: "xSLG", fullName: "期待長打率", category: "sabermetrics",
    description: "打球の質から見積もる長打力。", interpretation: "打者は高いほど長打性の打球が多い。", advanced: true, format: "rate", precision: 3 },
  exitVelocity: { id: "exitVelocity", version: "1", name: "打球速度", fullName: "平均打球速度", category: "batted-ball",
    description: "計測された打球の平均速度。", interpretation: "高いほど強い打球が多い傾向。", advanced: true, format: "decimal", precision: 1 },
  verticalMovement: { id: "verticalMovement", version: "1", name: "縦変化", fullName: "投球の縦方向の変化量", category: "pitching-analysis",
    description: "提供元の座標基準で見た投球の縦変化。", interpretation: "球種・座標定義が同じデータ同士で比較する。", advanced: true, format: "decimal", precision: 1 },
  horizontalMovement: { id: "horizontalMovement", version: "1", name: "横変化", fullName: "投球の横方向の変化量", category: "pitching-analysis",
    description: "提供元の座標基準で見た投球の横変化。", interpretation: "左右の向きと座標定義を確認して比較する。", advanced: true, format: "decimal", precision: 1 },
};
export function ratio(numerator: number, denominator: number): MetricValue {
  return denominator === 0
    ? { status: "missing", reason: "計算に必要な出場機会がありません" }
    : { status: "available", value: numerator / denominator };
}
