import { describe, expect, it } from "vitest";
import { evaluateWatch, emptyWatchState, watchFresh, watchObservationSchema, type WatchObservation } from "../src/domain/personal-watch";
import { PersonalWatch, PERSONAL_WATCH_KEY } from "../src/application/personal-watch";
import { leagueSwitchPath } from "../src/domain/cross-league";
import { parentNativeRoute } from "../src/domain/native-navigation";
const id = "00000000-0000-4000-8000-000000000001", game = "npb:game:01234567890123456789", now = Date.parse("2026-10-08T01:00:00Z");
function observation(patch: Partial<WatchObservation> = {}): WatchObservation { return { key:"result",league:"NPB",kind:"player",entityId:id,name:"選手",rule:"result",season:2026,competition:"regular",effectiveDate:"2026-10-07",generatedAt:"2026-10-07T22:00:00Z",eventDate:"2026-10-07",coverage:"partial",path:`/NPB/games/${encodeURIComponent(game)}`,metric:"Game",values:{gameId:game,gameNumber:1,H:1},collectionOnly:false,observedAt:now,...patch }; }
function changed(a:WatchObservation,b:WatchObservation) { return evaluateWatch(evaluateWatch(emptyWatchState(),[a],now),[b],now+100); }
describe("deterministic personal Watch",()=>{
  it("keeps independent Recent and milestone rules active with player-record alerts OFF",()=>{const s=emptyWatchState();s.preferences.players=false;s.preferences.recent=true;const a=observation({rule:"recent",metric:"OPS",coverage:"complete",values:{value:.8,sample:30}});const b=evaluateWatch(s,[a],now);expect(evaluateWatch(b,[{...a,values:{value:.9,sample:30}}],now).alerts).toHaveLength(1);const m=observation({rule:"milestone",coverage:"complete",values:{value:19,step:10}});expect(evaluateWatch(evaluateWatch(s,[m],now),[{...m,values:{value:20,step:10}}],now).alerts).toHaveLength(1);expect(evaluateWatch(evaluateWatch(s,[observation()],now),[observation({values:{gameId:game,gameNumber:1,H:2}})],now).alerts).toHaveLength(0);});
  it("requires generatedAt to reach the effective date in JST, including the UTC boundary",()=>{const earlier=observation({generatedAt:"2026-10-06T03:00:00Z"}), boundary=observation({generatedAt:"2026-10-06T15:00:00Z"});expect(watchFresh(earlier,now)).toBe(false);expect(watchFresh(boundary,now)).toBe(true);const s=evaluateWatch(emptyWatchState(),[observation()],now);const r=evaluateWatch(s,[{...earlier,values:{gameId:game,gameNumber:1,H:3}}],now);expect(r.alerts).toHaveLength(0);expect(r.observations[0]?.values.H).toBe(1);});
  it("starts with a baseline and suppresses regenerated identical Facts",()=>{const a=observation(), s=evaluateWatch(emptyWatchState(),[a],now);expect(s.alerts).toHaveLength(0);expect(evaluateWatch(s,[{...a,generatedAt:"2026-10-08T00:00:00Z"}],now+100).alerts).toHaveLength(0);});
  it("detects a new result and a correction separately without altering Facts",()=>{const a=observation(), b=observation({values:{gameId:game,gameNumber:1,H:2}});expect(changed(a,b).alerts[0]?.title).toContain("数値が変化");const g="npb:game:01234567890123456780";expect(changed(a,{...b,path:`/NPB/games/${g}`,values:{gameId:g,gameNumber:2,H:2}}).alerts[0]?.title).toContain("新しく確認");expect(a.values.H).toBe(1);});
  it.each(["2026-09-30","2026-10-09"])("ignores stale/future effectiveDate %s",date=>{const a=observation({effectiveDate:date,eventDate:null,generatedAt:null});expect(watchFresh(a,now)).toBe(false);expect(evaluateWatch(emptyWatchState(),[a],now).observations).toHaveLength(0);});
  it("does not roll back a newer baseline or silently accept older doubleheader results",()=>{const a=observation({values:{gameId:game,gameNumber:2,H:1}}), b=observation({values:{gameId:game,gameNumber:1,H:3}});expect(changed(a,b).observations[0]?.values.gameNumber).toBe(2);expect(changed(a,{...b,generatedAt:"2026-10-07T21:00:00Z"}).alerts).toHaveLength(0);});
  it("gates Recent by both samples, coverage, metric completeness and thresholds",()=>{const a=observation({rule:"recent",metric:"OPS",coverage:"complete",values:{value:.8,sample:20}}), b={...a,values:{value:.85,sample:25}};const s=emptyWatchState();s.preferences.recent=true;const baseline=evaluateWatch(s,[a],now);expect(evaluateWatch(baseline,[b],now).alerts).toHaveLength(1);for(const p of [{coverage:"partial" as const},{values:{value:.84,sample:25}},{values:{value:.9,sample:19}},{values:{value:null,sample:25}}])expect(evaluateWatch(baseline,[{...b,...p}],now).alerts).toHaveLength(0);});
  it("uses outs for pitching sample and a higher Collection-only threshold",()=>{const s=emptyWatchState();s.preferences.recent=s.preferences.collections=true;const a=observation({rule:"recent",metric:"ERA",coverage:"complete",collectionOnly:true,values:{value:2,sample:9}}), base=evaluateWatch(s,[a],now);expect(evaluateWatch(base,[{...a,values:{value:3,sample:9}}],now).alerts).toHaveLength(0);expect(evaluateWatch(base,[{...a,values:{value:3.5,sample:9}}],now).alerts).toHaveLength(1);});
  it("only detects confirmed exact streaks, including an ended streak",()=>{const a=observation({rule:"streak",metric:"安打",coverage:"complete",values:{value:4,atLeast:"false"}}), b={...a,values:{value:0,atLeast:"false"}};expect(changed(a,b).alerts).toHaveLength(1);expect(changed(a,{...b,values:{value:5,atLeast:"true"}}).alerts).toHaveLength(0);expect(changed({...a,coverage:"partial"},b).alerts).toHaveLength(0);});
  it("distinguishes stored-Season checkpoint proximity/arrival and blocks incomplete Career claims",()=>{const a=observation({rule:"milestone",metric:"HR",coverage:"complete",values:{value:18,step:10}});expect(changed(a,{...a,values:{value:19,step:10}}).alerts[0]?.title).toContain("20まで残り1");expect(changed(a,{...a,values:{value:20,step:10}}).alerts[0]?.priority).toBe("high");expect(changed({...a,coverage:"partial"},{...a,values:{value:20,step:10}}).alerts).toHaveLength(0);});
  it("compares Saved View membership instead of order and detects only new canonical matches",()=>{const a=observation({kind:"view",entityId:id,rule:"view",path:"/NPB/library?tab=views",coverage:"complete",values:{count:0},members:[]}), b={...a,values:{count:1},members:[id]};const s=emptyWatchState();s.preferences.savedViews=true;const base=evaluateWatch(s,[a],now);expect(evaluateWatch(base,[b],now).alerts).toHaveLength(1);expect(evaluateWatch(base,[{...b,coverage:"partial"}],now).alerts).toHaveLength(0);});
  it("keeps Historical differences historical and rejects MLB Current / NPB Postseason",()=>{const a=observation({league:"MLB",entityId:`mlb:player:${id}`,season:2025,effectiveDate:"2025-09-28",generatedAt:null,eventDate:null,path:`/MLB/players/mlb:player:${id}`,rule:"streak",metric:"安打",coverage:"complete",values:{value:1,atLeast:"false"}});expect(watchFresh(a,now)).toBe(true);expect(changed(a,{...a,values:{value:2,atLeast:"false"}}).alerts[0]?.title).toContain("保存済み");expect(watchFresh({...a,season:2026,effectiveDate:"2026-10-07"},now)).toBe(false);expect(watchObservationSchema.safeParse(observation({competition:"postseason"})).success).toBe(false);});
  it("blocks unknown coverage, cross-league identities, duplicate inputs and scope collisions",()=>{expect(evaluateWatch(emptyWatchState(),[observation({coverage:"unknown"})],now).observations).toHaveLength(0);expect(watchObservationSchema.safeParse(observation({entityId:`mlb:player:${id}`})).success).toBe(false);expect(()=>evaluateWatch(emptyWatchState(),[observation(),observation()],now)).toThrow("Duplicate");expect(()=>changed(observation(),observation({metric:"different"}))).toThrow("collision");});
  it("keeps Watch in My on native Back and league switching",()=>{expect(parentNativeRoute("/NPB/watch-center")).toBe("/NPB/my");expect(leagueSwitchPath("/NPB/watch-center","?season=2026","MLB")).toBe("/MLB/watch-center");});
});
describe("isolated Watch persistence",()=>{
  function setup(){const data=new Map<string,string>(),storage={get:async(k:string)=>data.get(k)??null,set:async(k:string,v:string)=>{data.set(k,v);}};return{data,storage,store:new PersonalWatch(storage,()=>now)};}
  it("persists unread/read/dismissal tombstones across reload and doesn't replay the same Fact",async()=>{const {store,storage}=setup(),a=observation(),b=observation({values:{gameId:game,gameNumber:1,H:2}});await store.observe([a]);const s=await store.observe([b]);expect(s.alerts[0]?.read).toBe(false);await store.markRead();expect((await new PersonalWatch(storage,()=>now).read()).alerts[0]?.read).toBe(true);await store.dismiss(s.alerts[0]!.id);await store.observe([a]);await store.observe([b]);expect((await store.read()).alerts).toHaveLength(1);expect((await store.read()).alerts[0]?.dismissed).toBe(true);});
  it("changes preferences serially, resets baselines and preserves existing alerts",async()=>{const {store}=setup();await Promise.all([store.preference("players",false),store.preference("recent",true)]);expect((await store.read()).preferences).toMatchObject({players:false,recent:true});await store.observe([observation()]);await store.preference("players",true);expect((await store.read()).observations).toHaveLength(0);expect((await store.observe([observation({values:{gameId:game,gameNumber:1,H:3}})])).alerts).toHaveLength(0);});
  it("prunes removed subscriptions while preserving baselines for failed reads of active targets",async()=>{const {store}=setup();await store.observe([observation()]);await store.observe([],"NPB",[`player:${id}`]);expect((await store.read()).observations).toHaveLength(1);await store.observe([],"NPB",[]);expect((await store.read()).observations).toHaveLength(0);});
  it.each(["bad-json",JSON.stringify({...emptyWatchState(),schemaVersion:99})])("keeps corrupt/unknown versions until explicit reset; other namespaces untouched",async raw=>{const {data,store}=setup();data.set(PERSONAL_WATCH_KEY,raw);data.set("baseball:favorites:v1","keep");await expect(store.read()).rejects.toThrow();expect(data.get(PERSONAL_WATCH_KEY)).toBe(raw);await store.reset();expect(data.get("baseball:favorites:v1")).toBe("keep");expect((await store.read()).alerts).toEqual([]);});
  it("migrates v0 and seeds dedup, preserving data",async()=>{const {data,store}=setup();data.set(PERSONAL_WATCH_KEY,JSON.stringify({...emptyWatchState(),schemaVersion:0,seen:undefined,checkedAt:undefined}));expect((await store.read()).schemaVersion).toBe(1);await store.markRead();expect(JSON.parse(data.get(PERSONAL_WATCH_KEY)!).schemaVersion).toBe(1);});
  it("expires old alerts on offline read and keeps legacy local view IDs without treating them as canonical players",async()=>{const {data,store,storage}=setup();await store.observe([observation()]);await store.observe([observation({values:{gameId:game,gameNumber:1,H:2}})]);const before=data.get(PERSONAL_WATCH_KEY);expect((await new PersonalWatch(storage,()=>now+91*86400000).read()).alerts).toHaveLength(0);expect(data.get(PERSONAL_WATCH_KEY)).toBe(before);expect(watchObservationSchema.safeParse(observation({kind:"view",entityId:"legacy-view-1",rule:"view",path:"/NPB/library?tab=views"})).success).toBe(true);expect(watchObservationSchema.safeParse(observation({path:"/NPB/games/%ZZ"})).success).toBe(false);});
  it("does not advance persisted observations on quota failure",async()=>{const {data,storage,store}=setup();await store.observe([observation()]);const before=data.get(PERSONAL_WATCH_KEY);await expect(new PersonalWatch({...storage,set:async()=>{throw Error("quota");}},()=>now).observe([observation({values:{gameId:game,gameNumber:1,H:3}})])).rejects.toThrow("保存できません");expect(data.get(PERSONAL_WATCH_KEY)).toBe(before);});
  it("bounds retained alerts and observations, expires old data",()=>{let s=emptyWatchState();for(let n=0;n<120;n++)s=evaluateWatch(s,[observation({values:{gameId:game,gameNumber:1,H:n}})],now+n);expect(s.alerts).toHaveLength(100);expect(s.seen).toHaveLength(120);const expired=evaluateWatch(s,[],now+91*86400000);expect(expired.alerts).toHaveLength(0);expect(expired.observations).toHaveLength(0);});
});
