import { describe, expect, it, vi } from "vitest";
import { readWatchObservations, watchTargets, type watchSources } from "../src/application/watch-observations";
import { defaultWatchPreferences, evaluateWatch, emptyWatchState, watchObservationSchema } from "../src/domain/personal-watch";
import type { PersonalState } from "../src/application/personal-library";
import type { Favorite } from "../src/domain/models";
const id="00000000-0000-4000-8000-000000000001", game="npb:game:01234567890123456789", date="2026-10-07", gen="2026-10-07T22:00:00Z", now=Date.parse("2026-10-08T01:00:00Z");
const library=():PersonalState=>({version:1,views:[],collections:[],activity:[]});
const favorite=(entityId=id,kind:Favorite["kind"]="player",league:Favorite["league"]="NPB"):Favorite=>({league,kind,entityId,addedAt:gen});
const m=(value:number|null,status="complete")=>({value,status});
function setup(){
  const directory={effectiveDate:date,generatedAt:gen,players:[{playerId:id,displayName:"選手",teamId:"npb:team:tigers"}],teams:[{id:"npb:team:tigers",name:"阪神"}]};
  const row={playerId:id,displayName:"選手",teamId:"npb:team:tigers",batting:{metrics:{PA:m(30),OPS:m(.8),H:m(49),HR:m(19)}},pitching:null};
  const recent={effectiveDate:date,generatedAt:gen,coverage:{status:"complete"},players:[row]};
  const log={playerId:id,batting:[{gameId:game,date,gameNumber:1,status:"final",hits:2,homeRuns:1,pa:4}],pitching:[]};
  const mocks={directory:vi.fn().mockResolvedValue(directory),log:vi.fn().mockResolvedValue(log),manifest:vi.fn().mockResolvedValue({effectiveDate:date,generatedAt:gen}),page:vi.fn().mockResolvedValue({date,generatedAt:gen,games:[]}),recent:vi.fn().mockResolvedValue(recent),season:vi.fn().mockResolvedValue({...recent,season:2026,players:[{playerId:id,checkpoints:[{metric:"HR",count:19}]}]}),historical:vi.fn()};
  const sources={directory:{findLatestNpb:mocks.directory},gameLog:{find:mocks.log},gameSurface:{manifest:mocks.manifest,date:mocks.page},recent:mocks.recent,checkpoints:mocks.season,historical:mocks.historical} as unknown as ReturnType<typeof watchSources>;
  return{sources,mocks,directory,recent,row};
}
describe("bounded Watch data acquisition",()=>{
  it("doesn't fetch anything without active tracked targets",async()=>{const {sources,mocks}=setup();const result=await readWatchObservations("NPB",[],library(),defaultWatchPreferences(),sources,now);expect(result.fetches).toBe(0);expect(mocks.directory).not.toHaveBeenCalled();});
  it("prioritizes Favorites, deduplicates Collections and bounds 12/4/6 targets",()=>{const l=library();l.collections=[{id:"collection",name:"若手",updatedAt:now,players:[{league:"NPB",playerId:id},...Array.from({length:25},(_,n)=>({league:"NPB" as const,playerId:`00000000-0000-4000-8000-${String(n+2).padStart(12,"0")}`}))]}];const p={...defaultWatchPreferences(),collections:true};const t=watchTargets("NPB",[favorite()],l,p);expect(t.players).toHaveLength(12);expect(t.players[0]).toEqual({id,collectionOnly:false});expect(t.omitted).toBe(14);});
  it("reads bulk Recent once, emits canonical record/checkpoint observations and no initial alerts",async()=>{const {sources,mocks}=setup(), prefs={...defaultWatchPreferences(),recent:true};const result=await readWatchObservations("NPB",[favorite()],library(),prefs,sources,now);expect(result.fetches).toBe(4);expect(mocks.recent).toHaveBeenCalledTimes(1);expect(result.observations.every(o=>watchObservationSchema.safeParse(o).success)).toBe(true);expect(result.observations.find(o=>o.rule==="recent")?.values).toEqual({value:.8,sample:30});expect(evaluateWatch(emptyWatchState(),result.observations,now).alerts).toHaveLength(0);});
  it("doesn't make incomplete coverage look like a verified milestone or saved-condition alert",async()=>{const {sources,mocks,recent}=setup();mocks.recent.mockResolvedValue({...recent,coverage:{status:"partial"}});mocks.season.mockResolvedValue({...recent,coverage:{status:"partial"}});const l=library();l.views=[{id,name:"条件",league:"NPB",kind:"data",conditions:"period=14&metric1=OPS&value1=.9",savedAt:now}];const result=await readWatchObservations("NPB",[favorite()],l,{...defaultWatchPreferences(),recent:true,savedViews:true},sources,now);expect(result.observations.some(o=>["milestone","view"].includes(o.rule))).toBe(false);expect(result.notes.join()).toContain("Coverage");});
  it("retains active identity keys on partial acquisition failure",async()=>{const {sources,mocks}=setup();mocks.directory.mockRejectedValue(Error("offline"));const result=await readWatchObservations("NPB",[favorite()],library(),defaultWatchPreferences(),sources,now);expect(result.activeEntities).toEqual([`player:${id}`]);expect(result.observations).toEqual([]);});
  it("rejects mixed publication generations for Season and team dates",async()=>{const {sources,mocks,recent}=setup();mocks.season.mockResolvedValue({...recent,generatedAt:"2026-10-07T21:00:00Z"});mocks.page.mockResolvedValue({generatedAt:"2026-10-07T21:00:00Z",games:[{gameId:game,date,gameNumber:1,status:"final",completeness:"complete",home:{id:"npb:team:tigers",score:2},away:{id:"npb:team:carp",score:0}}]});const result=await readWatchObservations("NPB",[favorite(),favorite("npb:team:tigers","team")],library(),defaultWatchPreferences(),sources,now);expect(result.observations.some(o=>o.rule==="milestone"||o.kind==="team")).toBe(false);});
  it("uses actual Saved View period/filter/minimum and doesn't persist searches or conditions",async()=>{const {sources,mocks}=setup(), l=library();l.views=[{id,name:"条件",league:"NPB",kind:"data",conditions:"period=7&season=2026&minimum=20&metric1=OPS&value1=.7&q=選手",savedAt:now}];const result=await readWatchObservations("NPB",[],l,{...defaultWatchPreferences(),savedViews:true},sources,now);expect(mocks.recent.mock.calls[0]?.[0]).toBe(7);expect(result.observations[0]?.members).toEqual([id]);expect(JSON.stringify(result.observations)).not.toContain("q=");expect(result.observations[0]?.path).toBe("/NPB/library?tab=views");});
  it("doesn't silently turn a selected Recent cohort into an all-player alert",async()=>{const {sources}=setup(),l=library();l.views=[{id,name:"条件",league:"NPB",kind:"data",conditions:`period=14&recentPlayers=${id}`,savedAt:now}];const result=await readWatchObservations("NPB",[],l,{...defaultWatchPreferences(),savedViews:true},sources,now);expect(result.observations).toEqual([]);});
  it("doesn't infer streaks from NPB's truncated game log or fetch raw PA",async()=>{const {sources,mocks}=setup();const result=await readWatchObservations("NPB",[favorite()],library(),defaultWatchPreferences(),sources,now);expect(result.observations.some(o=>o.rule==="streak")).toBe(false);expect(mocks.log).toHaveBeenCalledWith(id,10,0);expect(mocks.historical).not.toHaveBeenCalled();});
  it("observes only explicitly scheduled next games inside the published calendar",async()=>{const {sources,mocks}=setup();mocks.manifest.mockResolvedValue({effectiveDate:date,generatedAt:gen,from:"2026-03-27",to:"2026-10-09"});mocks.page.mockImplementation(async(d:string)=>({date:d,generatedAt:gen,games:d==="2026-10-08"?[{gameId:game,date:d,gameNumber:1,status:"scheduled",scheduledTime:"18:00",home:{id:"npb:team:tigers",name:"阪神",score:null},away:{id:"npb:team:carp",name:"広島",score:null}}]:[]}));const r=await readWatchObservations("NPB",[favorite("npb:team:tigers","team")],library(),defaultWatchPreferences(),sources,now);const next=r.observations.find(o=>o.rule==="next");expect(next?.eventDate).toBe("2026-10-08");expect(next?.values.opponent).toBe("広島");expect(watchObservationSchema.safeParse(next).success).toBe(true);expect(r.fetches).toBe(7);});
  it("keeps MLB Historical archival, never requests Current and doesn't infer a new event on first view",async()=>{const {sources,mocks}=setup(),mid=`mlb:player:${id}`,mg=`mlb:game:${id}`;
    mocks.historical.mockImplementation(async(path:string)=>path==="manifest.json"?{seasons:[{season:2025,coverage:"complete",firstDate:"2025-03-18",lastDate:"2025-09-28"}],teams:[]}:path==="chronology/2025.json"?{season:2025,competitionType:"regular",games:[{gameId:mg,number:1}]}:{player:{id:mid,name:"Historical選手",seasons:[2025]},seasonTotals:{},batting:[{playerId:mid,gameId:mg,season:2025,date:"2025-09-28",pa:4,ab:4,hits:1,doubles:0,triples:0,homeRuns:0,bb:0,hbp:0,sf:0}],pitching:[]});
    const result=await readWatchObservations("MLB",[favorite(mid,"player","MLB")],library(),defaultWatchPreferences(),sources,now);expect(result.observations.every(o=>o.season===2025&&o.league==="MLB")).toBe(true);expect(evaluateWatch(emptyWatchState(),result.observations,now).alerts).toHaveLength(0);expect(mocks.historical.mock.calls.every(([path])=>!String(path).includes("2026"))).toBe(true);
  });
});

